### ISSUE TITLE
[Wynncraft Ultimate] [Mod Suggestion] Voices of Wynn

### ISSUE THREAD

**Issue by sandstripes** [Spellbook-Studios/Modpacks#1]
Voices of Wynn adds voice acting to Wynncraft, which is amazing for immersion. It just got approved on Modrinth 11 minutes ago https://modrinth.com/mod/vow

**Comment by Seba244c** [comment]
YEEEEEEEEEES!!! It finally got approved, I will push out a new version soon. Thanks for the update :D

**Comment by Seba244c** [comment]
Having some troubles with getting VoW working.
Tried converting the modpack to fabric, but that didn't help.
![ih3x2fm](https://github.com/Spellbook-Studios/Modpacks/assets/23051740/3b04ec4b-842d-46da-a5fb-c17eff131c65)

**Comment by Seba244c** [comment]
![coht59t](https://github.com/Spellbook-Studios/Modpacks/assets/23051740/51b53bf6-0cda-4aa4-b737-95b58ef2cfdf)

Turns out, this is not supposed to be used yet. Closing this issue for now
